### ISSUE TITLE
Application only starts if geometries are specified from CLI.

### ISSUE THREAD

**Issue by ocsmit** [HuidaeCho/projpicker-gui#4]
Application will only start up if geometry is specifed from CLI. 

Traceback is 
```shell
Traceback (most recent call last):
  File "/home/owen/Work/ProjPicker/projpicker-gui/projpicker-gui/./gui.py", line 529, in <module>
    sys.exit(main())
  File "/home/owen/Work/ProjPicker/projpicker-gui/projpicker-gui/./gui.py", line 523, in main
    ppik_gui = ProjPickerGUI(layout, geoms, None, title="ProjPicker GUI")
  File "/home/owen/Work/ProjPicker/projpicker-gui/projpicker-gui/./gui.py", line 157, in __init__
    self.add_logical_buttons(logical_buttons_parent)
  File "/home/owen/Work/ProjPicker/projpicker-gui/projpicker-gui/./gui.py", line 206, in add_logical_buttons
    self.switch_logical_operator("and")
  File "/home/owen/Work/ProjPicker/projpicker-gui/projpicker-gui/./gui.py", line 358, in switch_logical_operator
    if self.geoms is not None and self.geoms[0] == op == "postfix":
IndexError: list index out of range
```

**Comment by HuidaeCho** [comment]
I'll fix it in an hour.

**Comment by ocsmit** [comment]
Will it be a part of a bigger update? I don't want to start making changes to the main branch if so.

**Comment by HuidaeCho** [comment]
No, this is it. You can start making changes.

**Comment by HuidaeCho** [comment]
@ocsmit Just so you know. To support any query that cannot be recreated using `and`, `or`, `xor` in the first line (non-`postfix` mode), let's use `self.geoms` to keep user query, just like I'm doing right now. That'll make things easier. `self.geoms` contains string lines, not parsed geometries, so basically `text.split("\n")`.
